# Generated by Django 5.2.8 on 2025-11-25 01:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False)),
                ('effect', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False)),
                ('baseHP', models.FloatField()),
                ('growthHP', models.FloatField()),
                ('baseAtk', models.FloatField()),
                ('growthAtk', models.FloatField()),
                ('baseExp', models.IntegerField()),
                ('growthExp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Droptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('itemName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('monsterName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop', to='game.monster')),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.FloatField(default=0)),
                ('maxHP', models.IntegerField(default=10)),
                ('currentHP', models.IntegerField(default=10)),
                ('maxMP', models.IntegerField(default=10)),
                ('currentMP', models.IntegerField(default=10)),
                ('staffDamage', models.FloatField(default=0)),
                ('staffCoolReduce', models.FloatField(default=0)),
                ('staffManaReduce', models.FloatField(default=0)),
                ('staffDefense', models.FloatField(default=0)),
                ('staffLuk', models.FloatField(default=0)),
                ('lowGemCount', models.IntegerField(default=0)),
                ('midGemCount', models.IntegerField(default=0)),
                ('highGemCount', models.IntegerField(default=0)),
                ('superGemCount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
