# Generated by Django 5.2.8 on 2025-11-21 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False)),
                ('effect', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False)),
                ('baseHP', models.FloatField()),
                ('growthHP', models.FloatField()),
                ('baseAtk', models.FloatField()),
                ('growthAtk', models.FloatField()),
                ('baseExp', models.IntegerField()),
                ('growthExp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Droptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('itemName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('monsterName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop', to='game.monster')),
            ],
        ),
    ]
