# Generated by Django 5.2.4 on 2025-11-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
