# Generated by Django 5.2.8 on 2025-11-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nowLocation',
            field=models.CharField(default='mainScene'),
        ),
    ]
