# Generated by Django 5.2.4 on 2025-12-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_nowlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='highGemCount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lowGemCount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='midGemCount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='superGemCount',
        ),
        migrations.AddField(
            model_name='player',
            name='coolReduceGem',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='damageGem',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='defenseGem',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='lukGem',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='manaReduceGem',
            field=models.FloatField(default=0),
        ),
    ]
