# Generated by Django 5.2.4 on 2025-12-17 22:40

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_skilllevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='itemSlots',
            field=models.JSONField(default=game.models.defaultItemSlot),
        ),
        migrations.AlterField(
            model_name='slot',
            name='skillSlots',
            field=models.JSONField(default=game.models.defaultSkillSlot),
        ),
    ]
