# Generated by Django 5.2.4 on 2025-12-18 07:22

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_slot_itemslots_alter_slot_skillslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nowLocation',
            field=models.CharField(default='CastleWall'),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='skillLev',
            field=models.JSONField(default=game.models.defaultSkillLevel),
        ),
    ]
