# Generated by Django 5.2.4 on 2025-12-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_player_nowlocation_alter_skilllevel_skilllev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='currentHP',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='currentMP',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='player',
            name='maxHP',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='maxMP',
            field=models.IntegerField(default=60),
        ),
    ]
