# Generated by Django 5.2.4 on 2025-12-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstScene',
            field=models.BooleanField(default=False),
        ),
    ]
